flowchart TD
    AAAA[Input2] -->|Get money| BBBB(Go shopping)
    BBBB --> CCCC{Let me think}
    CCCC -->|One| DDDD[Laptop]
    CCCC -->|Two| EEEE[iPhone]
    CCCC -->|Three| STARTSTATEe[START_STATE]